<p>
	Module Links:
	<a href="<?php echo $this->url('user');?>"><?php echo $this->translate('User'); ?></a> |
	
	<a href="<?php echo $this->url('login');?>"><?php echo $this->translate('Login'); ?></a> |

	<a href="<?php echo $this->url('registration');?>"><?php echo $this->translate('Register'); ?></a> |

	<a href="<?php echo $this->url('forgotten-password');?>"><?php echo $this->translate('Forgotten Password'); ?></a>
</p>
<hr />
<h2>Change Password</h2>
<div style="border: dashed 1px #ccc; border-radius: 15px;padding: 10px; width: 220px;">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('changePassword'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('currentPassword'));
echo $this->formRow($form->get('newPassword'));
echo $this->formRow($form->get('newPasswordConfirm'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
<p>
	<a href="<?php echo $this->url('user');?>"><?php echo $this->translate('Home page'); ?></a> |  
	<a href="<?php echo $this->url('changeEmail');?>"><?php echo $this->translate('Change Email'); ?></a>
</p>

</div>
<br/>
<?php echo '<div style="font-size: 20px; color: red;">' . $this->messages . '</div>'; ?>