<p>
	Module Links:
	<a href="<?php echo $this->url('user');?>"><?php echo $this->translate('User'); ?></a> |
	
	<a href="<?php echo $this->url('login');?>"><?php echo $this->translate('Login'); ?></a> |

	<a href="<?php echo $this->url('registration');?>"><?php echo $this->translate('Register'); ?></a> |

	<a href="<?php echo $this->url('forgotten-password');?>"><?php echo $this->translate('Forgotten Password'); ?></a>
</p>
<hr />
<h2><?php echo sprintf($this->translate('Confirmation successful! You have a new password. An e-mail has been sent to %s with a new password.'), $email);?></h2>