<h2>An error occured during confirmation of change your password! Please, try again later. <?php echo $registrationToken?></h2>
<hr>
<p>
	<a href="<?php echo $this->url('csn-user/default', array('controller' => 'index', 'action' => 'login'));?>"><?php echo $this->translate('Go to login page'); ?></a> |

	<a href="<?php echo $this->url('csn-user/default', array('controller' => 'registration', 'action' => 'index'));?>"><?php echo $this->translate('Go to Registration.'); ?></a> |
</p>
</hr>