<h4 >
	<a href="<?php echo $this->url('user');?>" class="btn btn-success"><?php echo $this->translate('User'); ?></a>
<?php
	if (!$user = $this->identity()) {
?>
	<a href="<?php echo $this->url('login');?>" class="btn btn-success"><?php echo $this->translate('Login'); ?></a>
	<a href="<?php echo $this->url('registration');?>" class="btn btn-success"><?php echo $this->translate('Sing up'); ?></a>
	<a href="<?php echo $this->url('forgotten-password');?>" class="btn btn-success"><?php echo $this->translate('Forgotten Password'); ?></a>
<?php
	} else if ($user = $this->identity()) {
?>
	<a href="<?php echo $this->url('editProfile');?>" class="btn btn-success"><?php echo $this->translate('Edit Profile'); ?></a> 
	<a href="<?php echo $this->url('changeEmail');?>" class="btn btn-success"><?php echo $this->translate('Change email'); ?></a> 
	<a href="<?php echo $this->url('changePassword');?>" class="btn btn-success"><?php echo $this->translate('Change Password'); ?></a>
<?php } ?>
</h4>
<hr />
<div class="hero-unit">
<br />
<h2>Thank you! Your registration has been confirmed.</h2>
<br />
</div>