<p>
	Module Links:
	<a href="<?php echo $this->url('user');?>"><?php echo $this->translate('User'); ?></a> |
	
	<a href="<?php echo $this->url('login');?>"><?php echo $this->translate('Login'); ?></a> |

	<a href="<?php echo $this->url('registration');?>"><?php echo $this->translate('Register'); ?></a> |

	<a href="<?php echo $this->url('forgotten-password');?>"><?php echo $this->translate('Forgotten Password'); ?></a>
</p>
<hr />
<h2>Edit profile</h2>
<div style="border: dashed 1px #ccc; border-radius: 15px;padding: 10px; width: 220px;">
<?php

$form = $this->form;
$username = $this->username;
$email = $this->email;
$displayname = $this->displayname;
echo 'Username: '. $username.' ;)<br>';
echo 'Password: ';
?>
<a href="<?php echo $this->url('changePassword');?>"><?php echo $this->translate('Change password'); ?></a><br>
<?php
echo 'Email: '. $email .' ';
?>
<a href="<?php echo $this->url('changeEmail');?>"><?php echo $this->translate('Change email'); ?></a><br>
<?php
echo 'Display name: '. $displayname;
$form->setAttribute('action', $this->url('editProfile'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('displayName'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
<p>
	<a href="<?php echo $this->url('user');?>"><?php echo $this->translate('Home page'); ?></a> |  
	<a href="<?php echo $this->url('changePassword');?>"><?php echo $this->translate('Change password'); ?></a>
</p>
</div>
<br/>
<?php echo '<div style="font-size: 20px; color: red;">' . $this->messages . '</div>'; ?>