<?php
/**
 * CsnUser - Coolcsn Zend Framework 2 User Module
 * 
 * @link https://github.com/coolcsn/CsnUser for the canonical source repository
 * @copyright Copyright (c) 2005-2013 LightSoft 2005 Ltd. Bulgaria
 * @license https://github.com/coolcsn/CsnUser/blob/master/LICENSE BSDLicense
 * @author Stoyan Cheresharov <stoyan@coolcsn.com>
 * @author Svetoslav Chonkov <svetoslav.chonkov@gmail.com>
 * @author Nikola Vasilev <niko7vasilev@gmail.com>
 * @author Stoyan Revov <st.revov@gmail.com>
 * @author Martin Briglia <martin@mgscreativa.com>
 */

echo $this->partial('csn-user/layout/nav-menu', array('navMenu' => $this->navMenu, 'user' => $this->identity()));

$form = $this->form;

/**
 *
 * Set form fields classes and placeholders here
 *
 */

$form->setAttributes(array(
    'class' => 'form'
));

$form->get('firstName')->setAttributes(array(
    'required' => 'false',
    'class' => 'form-control input-lg', 
    'placeholder' => $this->translate('First Name')
));

$form->get('lastName')->setAttributes(array(
    'required' => 'false',
    'class' => 'form-control input-lg', 
    'placeholder' => $this->translate('Last Name')
));

$form->get('language')->setAttributes(array(
    'required' => 'true',
    'class' => 'form-control input-lg',
));

$form->get('submit')->setAttributes(array(
    'class' => 'btn btn btn-success btn-lg', 
    'value' => $this->translate('Update Profile')
));

$form->prepare();
?>
<div class="jumbotron">
  <h2><?php echo $this->translate('Edit Profile')?></h2>
    <div class="container" id="wrap">
	  <div class="row">
        <div class="col-md-8 col-md-offset-3">
          <?php echo $this->form()->openTag($form); ?>
            <div class="row">
              <div class="col-sm-12"> 
                <?php echo $this->message ?>      
              </div>
            </div>
            <div>
              <span class="zf-green" style="font-size: 24px;"><?php echo $this->translate('Your Username') ?>: </span><?php echo $this->username ?>
            </div>
            <div>
              <span class="zf-green" style="font-size: 24px;"><?php echo $this->translate('Your Password') ?>: </span>******
              <br />
              <a href="<?php echo $this->url('user-register', array('action' => 'change-password'));?>">
                <?php echo $this->translate('Change Password'); ?>
              </a>
            </div>
            <div>
              <span class="zf-green" style="font-size: 24px;"><?php echo $this->translate('Your Email') ?>: </span>
              <?php echo $this->email ?>
              <br/ >
              <a href="<?php echo $this->url('user-register', array('action' => 'change-email'));?>">
                <?php echo $this->translate('Change Email'); ?>
              </a>
            </div>
            <div>
              <span class="zf-green" style="font-size: 24px;"><?php echo $this->translate('Your Security Question') ?>: </span>
              <?php echo $this->securityQuestion ?>
              <br/ >
              <a href="<?php echo $this->url('user-register', array('action' => 'change-security-question'));?>">
                <?php echo $this->translate('Change Security Question'); ?>
              </a>
            </div>
            <div>
              <span class="zf-green" style="font-size: 24px;"><?php echo $this->translate('Your First/Last Name') ?>:</span>
              <br/ >
	          <div class="row">
                <div class="col-md-6">
                <?php
                  $element = $form->get('firstName');
                  echo $this->formElement($element);
                  echo $this->formElementErrors($element);
                ?>
                </div>
                <div class="col-md-6">
                <?php
                  $element = $form->get('lastName');
                  echo $this->formElement($element);
                  echo $this->formElementErrors($element);
                ?>
                </div>
              </div>
              <span class="zf-green" style="font-size: 24px;"><?php echo $this->translate('Your Language') ?>:</span>
              <br/ >
              <?php
                $element = $form->get('language');
                echo $this->formElement($element);
                echo $this->formElementErrors($element);
              ?>
            </div>
            <div class="row">
              <div class="col-sm-12"> 
                <?php echo $this->formRow($form->get('submit'))?>              
              </div>
            </div>
          <?php 
            echo $this->formRow($form->get('csrf'));
            echo $this->form()->closeTag();
          ?>         
        </div>
      </div>            
    </div>
</div>
