<?php echo $this->partial('csn-user/layout/nav-menu', array('navMenu' => $this->navMenu)); ?>
<hr />
<div class="jumbotron">
<h2>Edit profile</h2>

<?php

$form = $this->form;
$username = $this->username;
$email = $this->email;
$displayname = $this->displayname;
echo 'Username: '. $username.' ;)<br>';
echo 'Password: ';
?>
<a href="<?php echo $this->url('changePassword');?>"><?php echo $this->translate('Change password'); ?></a><br>
<?php
echo 'Email: '. $email .' ';
?>
<a href="<?php echo $this->url('changeEmail');?>"><?php echo $this->translate('Change email'); ?></a><br>
<?php
echo 'Display name: '. $displayname;
$form->setAttribute('action', $this->url('editProfile'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('displayName'));
echo '<br />';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

<br/>
<?php echo '<div style="font-size: 20px; color: red;">' . $this->message . '</div>'; ?>
</div>
