<?php echo $this->partial('csn-user/layout/nav-menu', array('navMenu' => $this->navMenu)); ?>
<hr />
<div class="jumbotron">
<br />
<h2><?php echo $this->translate('Something went wrong when trying to send activation email! Please, try again later.') ?></h2>
<br />
</div>
<?php echo $this->partial('error/index', array('display_exceptions' =>  $this->display_exceptions, 'exception' => $this->exception, 'message' => $this->exception->getMessage())); ?>
