<h2>Please fill the form and hit the button.</h2>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('csn-user/default', array('controller' => 'registration', 'action' => 'forgotten-password')));
$form->prepare();

echo $this->form()->openTag($form);
echo '<hr>';
echo '<p>';
echo $this->formRow($form->get('email'));
echo '</p>';
echo '</hr>';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
<hr>
<p>
	<a href="<?php echo $this->url('csn-user/default', array('controller' => 'index', 'action' => 'login'));?>"><?php echo $this->translate('Go to login page'); ?></a> |
	<a href="<?php echo $this->url('csn-user/default', array('controller' => 'index', 'action' => 'index'));?>"><?php echo $this->translate('Back to Home page'); ?></a> |
	<a href="<?php echo $this->url('csn-user/default', array('controller' => 'registration', 'action' => 'index'));?>"><?php echo $this->translate('Go to Registration.'); ?></a> |
</p>
</hr>