<p>
	Module Links:
	<a href="<?php echo $this->url('user');?>"><?php echo $this->translate('User'); ?></a> |
	
	<a href="<?php echo $this->url('login');?>"><?php echo $this->translate('Login'); ?></a> |

	<a href="<?php echo $this->url('registration');?>"><?php echo $this->translate('Register'); ?></a> |

	<a href="<?php echo $this->url('forgotten-password');?>"><?php echo $this->translate('Forgotten Password'); ?></a>
</p>
<hr />
<h2>Forgotten password.</h2>
<div style="border: dashed 1px #ccc; border-radius: 15px;padding: 10px; width: 220px;">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('forgotten-password'));
$form->prepare();

echo $this->form()->openTag($form);
echo '<p>';
echo $this->formRow($form->get('usernameOrEmail'));
echo '</p>';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
echo '</div>';