<h4 >
	<a href="<?php echo $this->url('user');?>" class="btn btn-success"><?php echo $this->translate('User'); ?></a>
	<a href="<?php echo $this->url('login');?>" class="btn btn-success"><?php echo $this->translate('Login'); ?></a>
	<a href="<?php echo $this->url('registration');?>" class="btn btn-success"><?php echo $this->translate('Sing up'); ?></a>
	<a href="<?php echo $this->url('forgotten-password');?>" class="btn btn-success"><?php echo $this->translate('Forgotten Password'); ?></a>
<?php
	if ($user = $this->identity()) {
?>
	<a href="<?php echo $this->url('editProfile');?>" class="btn btn-success"><?php echo $this->translate('Edit Profile'); ?></a> 
	<a href="<?php echo $this->url('changeEmail');?>" class="btn btn-success"><?php echo $this->translate('Change email'); ?></a> 
	<a href="<?php echo $this->url('changePassword');?>" class="btn btn-success"><?php echo $this->translate('Change Password'); ?></a>
<?php } ?>
</h4>
<hr />
<div class="hero-unit">
<h2>Sign up</h2>
<?php

$form = $this->form;
$form->setAttribute('action', $this->url('registration'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('displayName'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('passwordConfirm'));
echo '<div style="width: 270px"';
echo $this->formRow($form->get('captcha'));
echo '</div>';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
</div>
