<?php echo $this->partial('csn-user/layout/nav-menu', array('navMenu' => $this->navMenu)); ?>
<hr />
<div class="jumbotron">
<h2>Sign up</h2>
<?php

$form = $this->form;
$form->setAttribute('action', $this->url('registration'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('username'));
echo '<br />';
echo $this->formRow($form->get('displayName'));
echo '<br />';
echo $this->formRow($form->get('email'));
echo '<br />';
echo $this->formRow($form->get('password'));
echo '<br />';
echo $this->formRow($form->get('passwordConfirm'));
echo '<br />';
echo '<div style="width: 270px"';
echo $this->formRow($form->get('captcha'));
echo '</div>';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
</div>
