<h2><?php echo sprintf($this->translate('An e-mail has been sent to %s. Please, check your inbox and confirm your request to change password!'), $email);?></h2>

<hr>
<p>
	<a href="<?php echo $this->url('csn-user/default', array('controller' => 'index', 'action' => 'login'));?>"><?php echo $this->translate('Go to login page'); ?></a> |
	<a href="<?php echo $this->url('csn-user/default', array('controller' => 'index', 'action' => 'index'));?>"><?php echo $this->translate('Back to Home page'); ?></a> |
</p>
</hr>