<p>
	Module Links:
	<a href="<?php echo $this->url('user');?>"><?php echo $this->translate('User'); ?></a> |
	
	<a href="<?php echo $this->url('login');?>"><?php echo $this->translate('Login'); ?></a> |

	<a href="<?php echo $this->url('registration');?>"><?php echo $this->translate('Register'); ?></a> |

	<a href="<?php echo $this->url('forgotten-password');?>"><?php echo $this->translate('Forgotten Password'); ?></a>
</p>
<?php 
if($user = $this->identity()) {
 ?>

<h4>Hi, <span style="color: #ADFF2F;"><?php echo $this->escapeHtml($user->getUsername()); ?>!</span>!		
 | <a href="<?php echo $this->url('logout');?>"><?php echo $this->translate('Logout'); ?></a>
</h4>

<?php 
}else{
	echo '<h4>Hi, <span  style="color: #FF8C00">Guest</span>!</h4>';
}