<h2>Login</h2>
<div style="border: dashed 1px #ccc; border-radius: 15px;padding: 10px; width: 220px;">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('csn-user/login'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));

echo $this->formRow($form->get('rememberme'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
<p>
	<a href="<?php echo $this->url('csn-user/registration');?>"><?php echo $this->translate('Register'); ?></a> |  
	<a href="<?php echo $this->url('csn-user/forgotten-password');?>"><?php echo $this->translate('Forgotten Password'); ?></a>
</p>
</div>
<br/>
<?php echo '<div style="font-size: 20px; color: red;">' . $this->messages . '</div>'; ?>
<br />
<p>
	<a href="<?php echo $this->url('csn-user');?>"><?php echo $this->translate('Back to Index Page'); ?></a>
</p>


